<a href="https://colab.research.google.com/github/GrandManager153/Mineria_De_Datos/blob/main/Mineria_Datos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Mineria de Datos

##Primer Parcial

###Introducción

####Conceptos

La minería de datos es una técnica asistida por computadora que se utiliza en los análisis para procesar y explorar grandes conjuntos de datos. Gracias a las herramientas y métodos de minería de datos, las organizaciones pueden descubrir patrones y relaciones ocultas en sus datos. La minería de datos transforma datos en bruto en conocimiento práctico. Las compañías utilizan dicho conocimiento para resolver problemas, analizar las consecuencias en el futuro de decisiones empresariales y aumentar sus márgenes de beneficio.

Es un término erróneo porque el objetivo de esta actividad no es extraer o minar los datos en sí. Más bien, ya existe una gran cantidad de datos, y la minería de datos extrae un significado o un conocimiento valioso de estos.

####Ciencia de Datos

Help and Documentation in Python

IPython Magic Commands

In [ ]:
# Sirve para evaluar el desempeño de una expresión en cuanto a tiempo
%timeit L = [n ** 2 for n in range(1000)]

87.7 µs ± 26.4 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [ ]:
# Con doble porcetanje podemos evaluar el desempeño en cuanto tiempo en más de una linea de codigo
%%timeit
L = []
for n in range(1000):
    L.append(n ** 2)

79.3 µs ± 979 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


IPython and Shell Commands

In [ ]:
!ls

sample_data


In [ ]:
!pwd

/content


In [ ]:
!echo "printing from the shell"

printing from the shell


In [ ]:
contents = !ls

In [ ]:
print(contents)

['sample_data']


In [ ]:
directory = !pwd

In [ ]:
print(directory)

['/content']


In [ ]:
type(directory)

IPython.utils.text.SList

In [ ]:
message = "hello from Python"

In [ ]:
!echo {message}

hello from Python


In [ ]:
%cd /content

/content


In [ ]:
%ls

sample_data/


In [ ]:
%cd /content/sample_data

/content/sample_data


In [ ]:
%ls

anscombe.json*                mnist_test.csv
california_housing_test.csv   mnist_train_small.csv
california_housing_train.csv  README.md*


Understanding Data Types in Python

In [3]:
# Importa numpy y lo renombra como np
import numpy as np

In [ ]:
# Arreglo lineal de enteros
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [ ]:
# Castea(cambia) la lista al primer valor que venga en ella
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [ ]:
# Se puede definir(implicitar) el tipo de datos en los que se quiere la lista
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [ ]:
# Cuando el argumento de np.array es una iteracion anidada genera una matriz(lista de listas)
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [ ]:
# Forma de impresion en python(lista de listas)
[range(i, i + 3) for i in [2, 4, 6]]

[range(2, 5), range(4, 7), range(6, 9)]

Creating Arrays from Scratch

In [6]:
# Forma de crear un arreglo lleno de 0
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [4]:
# Forma de crear un arreglo Bidimensional
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [5]:
# Forma de crear un arreglo bidimensional y que se llene de un solo dato
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [12]:
# Forma de crear un arreglo con una secuencia en este caso de cada 2
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [10]:
# Forma de crear un arreglo con 5 valores entre un rango
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [13]:
# Forma de crear un arreglo sobre la distribucion estandar
np.random.random((3, 3))

array([[0.94391615, 0.17047766, 0.31282787],
       [0.54886671, 0.1064598 , 0.62594798],
       [0.16590906, 0.99461087, 0.67682745]])

In [15]:
# Forma de crear un arreglo de datos aleatorios entre 0 y 1 sobre la forma de distribucion estandar
np.random.normal(0, 1, (3, 3))

array([[-0.27144349, -0.92123817, -1.81454122],
       [ 0.66834381,  0.1332676 ,  0.6493442 ],
       [-0.02198603, -1.70365502,  0.13005856]])

In [19]:
# Forma de crear un arreglo aleatorios de enteros en un intervalo entre entre 0 y 10
np.random.randint(0, 6, (3, 3))

array([[4, 3, 2],
       [2, 5, 4],
       [1, 4, 3]])

In [20]:
# Forma de crear una matriz como una matriz identidad
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
# Forma de crear un arreglo sin inicializar con enteros
np.empty(3)

array([1., 1., 1.])

The Basics of NumPy Arrays

In [41]:
# Creacion de diversos arreglos
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

In [23]:
# Caracteristicas de los valores dentro del arreglo
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


In [24]:
# Tipo de datos en el arreglo
print("dtype:", x3.dtype)

dtype: int64


In [25]:
# Tamaño de los datos en el arreglo y cuanto ocupan
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

itemsize: 8 bytes
nbytes: 480 bytes


Array Indexing: Accessing Single Elements

In [27]:
x1

array([5, 0, 3, 3, 7, 9])

In [32]:
x1[2]

np.int64(9)

In [33]:
x1[-1]

np.int64(9)

In [34]:
x1[-2]

np.int64(7)

In [42]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [43]:
x2[0, 2]

np.int64(2)

In [44]:
x2[-1, -1] = 12
x2

array([[ 3,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7, 12]])

##Segunda parte


Media

In [46]:
data = np.array((1, 2, 3, 4, 5))
weight = np.array((1, 2, 3, 4, 5))
promedio = np.average(data)
promedio_ponderado = np.average(data, weights=weight)

print(promedio)
print(promedio_ponderado)

3.0
3.6666666666666665


Mediana

In [47]:
mediana = np.median(data)
print(mediana)

3.0


Varianza y Desviacion Estandar

In [48]:
varianza = np.var(data)
desviacion_estandar = np.std(data)

print(varianza)
print(desviacion_estandar)

2.0
1.4142135623730951


Generacion de Datos Aleatorios

In [51]:
muestra = np.random.normal(0, 1, 1000)
print(np.mean(muestra), np.std(muestra))

0.033927549127831566 1.0001857121834128


Correlacion

In [53]:
corr = np.corrcoef((1, 2, 3), (1, 5, 7))
print(corr)

[[1.         0.98198051]
 [0.98198051 1.        ]]
