<a href="https://colab.research.google.com/github/GrandManager153/Mineria_De_Datos/blob/main/Mineria_Datos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Mineria de Datos

##Primer Parcial

###Introducción

####Conceptos

La minería de datos es una técnica asistida por computadora que se utiliza en los análisis para procesar y explorar grandes conjuntos de datos. Gracias a las herramientas y métodos de minería de datos, las organizaciones pueden descubrir patrones y relaciones ocultas en sus datos. La minería de datos transforma datos en bruto en conocimiento práctico. Las compañías utilizan dicho conocimiento para resolver problemas, analizar las consecuencias en el futuro de decisiones empresariales y aumentar sus márgenes de beneficio.

Es un término erróneo porque el objetivo de esta actividad no es extraer o minar los datos en sí. Más bien, ya existe una gran cantidad de datos, y la minería de datos extrae un significado o un conocimiento valioso de estos.

####Ciencia de Datos

Help and Documentation in Python

IPython Magic Commands

In [6]:
# Sirve para evaluar el desempeño de una expresión en cuanto a tiempo
%timeit L = [n ** 2 for n in range(1000)]

87.7 µs ± 26.4 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [7]:
# Con doble porcetanje podemos evaluar el desempeño en cuanto tiempo en más de una linea de codigo
%%timeit
L = []
for n in range(1000):
    L.append(n ** 2)

79.3 µs ± 979 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


IPython and Shell Commands

In [8]:
!ls

sample_data


In [9]:
!pwd

/content


In [10]:
!echo "printing from the shell"

printing from the shell


In [11]:
contents = !ls

In [12]:
print(contents)

['sample_data']


In [13]:
directory = !pwd

In [14]:
print(directory)

['/content']


In [15]:
type(directory)

IPython.utils.text.SList

In [16]:
message = "hello from Python"

In [17]:
!echo {message}

hello from Python


In [20]:
%cd /content

/content


In [21]:
%ls

sample_data/


In [22]:
%cd /content/sample_data

/content/sample_data


In [23]:
%ls

anscombe.json*                mnist_test.csv
california_housing_test.csv   mnist_train_small.csv
california_housing_train.csv  README.md*


Understanding Data Types in Python

In [29]:
# Importa numpy y lo renombra como np
import numpy as np

In [32]:
# Arreglo lineal de enteros
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [30]:
# Castea(cambia) la lista al primer valor que venga en ella
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [35]:
# Se puede definir(implicitar) el tipo de datos en los que se quiere la lista
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [36]:
# Cuando el argumento de np.array es una iteracion anidada genera una matriz(lista de listas)
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [37]:
# Forma de impresion en python(lista de listas)
[range(i, i + 3) for i in [2, 4, 6]]

[range(2, 5), range(4, 7), range(6, 9)]